name: dev_post
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  code style
  linter: ^1.27.0
  #  logging events
  logging: ^1.1.0
  #  http
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  #  work with datetime
  intl: ^0.17.0
  # state management
  flutter_riverpod: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_gen_runner: ^5.0.3
  flutter_lints: ^2.0.0
  freezed: ^2.2.0


flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: lib/src/assets/font/Ubuntu-Regular.ttf